### Faculty proposing for an event
POST http://localhost:1234/seminar/propose/data_ecr_workshop
Content-Type: application/json

{
  
    
    "http://172.20.176.72:1234":"Workshop",
    "event_title":"Express",
    "event_organizer":"CSE",
    "event_sponsor":"CSI & Management",
    "event_date":"2023-10-20",
    "event_venue":"Data analytics lab",
    "guest_name":"Mr. Razak Mohamed",
    "guest_designation":"Full stack trainer, Zealous",
    "guest_address":"Salem",
    "guest_number":8667002959,
    "guest_email":"razaksrmd@gmail.com",
    "student_count":64,
    "faculty_count":3,
    "others_count":0,
    "proposal_date":"",
    "proposal_hod":"",
    "proposal_principal":"",
    "event_budget":40000,
    "event_coordinator":"Victor Prakash",
  
    "coordinator_phno":9944085437,
    "coordinator_designation":406,
    "acdyr_id":"",
    "dept_id":1,
    "sem_id":1
}


####

PUT http://localhost:1234/seminar/ecrCompletion/data_management_seminar/5016
Content-Type: application/json

{
    "event_budget_utilized"
: 
"10",
"event_date_from"
: 
"2023-10-30",
"event_date_to"
: 
"2023-11-29",

"event_description"
: 
"demo",
"event_organizing_secretary"
: 
"Dr.G.Kavitha",
"event_photo_1"
: 
"Blockchain1_05-11-2023_20-53-41.png",
"event_photo_2"
: 
"Blockchain2_05-11-2023_20-53-41.png",
"event_po"
: 
"PO1, PO3",
"event_time"
: 
"20:59"
}

##
PUT http://localhost:1234/seminar/completionacknowledgelevel2/data_management_seminar/1/6000/5020


##

GET http://localhost:1234/seminar/getAcdYrWithSubType/3003

###

POST http://localhost:1234/seminar/ecrProposal/data_management_Seminar
Content-Type: application/json

{
    "report_id":"RPT5005",
    "http://172.20.176.72:1234":"seminar",
    "event_title":"Vue JS",
    "event_organizer":"CSE",
    "event_sponsor":"CSI & Management",
    "event_date":"2023-10-20",
    "event_venue":"Data analytics lab",
    "guest_name":"Mr. Razak Mohamed",
    "guest_designation":"Full stack trainer, Zealous",
    "guest_address":"Salem",
    "guest_phone_number":8667002959,
    "guest_email":"razaksrmd@gmail.com",
    "student_count":64,
    "faculty_count":3,
    "others_count":0,
    "event_budget":40000,
    "event_coordinator":"Victor Prakash",
    "coordinator_emp_id":6007,
    "coordinator_phone_number":9944085437,
    "coordinator_designation":406,
    "event_date_from":"0000-00-00",
    "event_date_to":"0000-00-00",
    "acdyr_id":3,
    "dept_id":4,
    "sem_id":1
}



###

GET http://localhost:1234/seminar/supply/Cloud-2023-09-11-1694405954

###

GET http://localhost:1234/seminar/dept/1

### HoD is receiving the requested proposal
GET http://localhost:1234/seminar/loadforlevel1/1/6001

###

### HoD approves the proposal
PUT http://localhost:1234/seminar/acknowledgelevel1/1/6001/1

###

### Principal is receiving the requested proposal
GET http://localhost:1234/seminar/loadforlevel2

###

### Principal approves the proposal
PUT http://localhost:1234/seminar/acknowedgelevel2/1/2

###

################## Proposal over #####################

###

### Faculty is receiving his/her proposal after approved
GET http://localhost:1234/ecrWorkshop/loadforCompletion/1

###

### Faculty is updating the completion report
PUT http://localhost:1234/ecrWorkshop/ecrCompletion/0000001
Content-Type: application/json

{
    "event_photo_1":"photo/path1",
    "event_photo_2":"photo/path2",
    "event_po":"1,2,3,4",
    "completion_date":"0000-00-00",
    "completion_hod":"0000-00-00",
    "completion_principal":"0000-00-00",
    "pdf":"pdf/path",
    "event_duration":"3hrs",
    "event_os":"Dr. G. Kavitha",
    "event_time":"10 am",
    "event_description":"The event was about how to develop a webpage using React JS",
    "event_budget_utilized":50000
}

###

### HoD is receiving the completion report
GET http://localhost:1234/ecrWorkshop/eventcompletionloadlevel1/1/6001

###

### HoD approves the completion report
PUT http://localhost:1234/ecrWorkshop/completionacknowledgelevel1/1/6001

###

### Principal is receiving the completion report
GET http://localhost:1234/ecrWorkshop/completionloadlevel2/1

###

### Principal approves the completion report
PUT http://localhost:1234/ecrWorkshop/completionacknowledgelevel2/1/RPT0000001


GET http://localhost:1234/seminar/find